name:                planet-haskell-jp
version:             0.1.0.0
github:              "matsubara0507/planet-haskell-jp"
license:             MIT
author:              "MATSUBARA Nobutada"
copyright:           "2018 MATSUBARA Nobutada"

extra-source-files:
- README.md

description:         Please see the README on Github at <https://github.com/matsubara0507/planet-haskell-jp#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  planet-haskell-jp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - planet-haskell-jp

tests:
  planet-haskell-jp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - planet-haskell-jp
